### ISSUE TITLE
Windows Defender krzyczy

### ISSUE THREAD

**Issue by DayidTempest** [jakub-sieradzki/DebloatWindows10#1]
Windows Defender krzyczy, że aplikacja może być niebezpieczna i bla bla bla. Nie da się tego usunąć, bo koledzy boją się korzystać?

**Comment by jakub-sieradzki** [comment]
Dziękuję za informację. Komunikat z Microsoft Defender SmartScreen wyświetla się ponieważ ten plik nie jest jeszcze znany Defenderowi, a dokładniej nie jest "popularny" wśród użytkowników. Drugą kwestią jest również brak podpisu cyfrowego aplikacji, co może naprawię już niebawem.

**Comment by jakub-sieradzki** [comment]
Niestety, certyfikaty dzięki którym wyświetlałbym się jako zweryfikowany wydawca kosztują fortunę, więc ta opcja odpada. A jeśli chodzi o popularność pliku, to mam nadzieję, że wkrótce trochę się zwiększy i komunikat SmartScreen już nie będzie się wyświetlał ;)
